// <auto-generated />
using System;
using Dsw2026Ej15.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dsw2026Ej15.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260731214649_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Dsw2026Ej15.Domain.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SpecialityId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SpecialityId");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("Dsw2026Ej15.Domain.Speciality", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Specialities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8a1f3b78-3f66-4d68-8d6e-1c5b9c7a2f41"),
                            Description = "Especialidad médica dedicada al diagnóstico, tratamiento y prevención de enfermedades del corazón y del sistema cardiovascular.",
                            Name = "Cardiología"
                        },
                        new
                        {
                            Id = new Guid("f4d2c9a1-7b3e-4f8d-9c61-2e7a5d8b3c12"),
                            Description = "Rama de la medicina que se ocupa de la salud integral de niños, niñas y adolescentes.",
                            Name = "Pediatría"
                        },
                        new
                        {
                            Id = new Guid("c7e8d4b2-5f91-4a37-b8d4-9e2c6f1a7b53"),
                            Description = "Especialidad enfocada en el estudio, diagnóstico y tratamiento de enfermedades de la piel, cabello y uñas.",
                            Name = "Dermatología"
                        },
                        new
                        {
                            Id = new Guid("1b9c5d7e-8a42-4f63-9d8e-3c7a1f5b2e64"),
                            Description = "Especialidad médica que trata los trastornos del sistema nervioso central y periférico.",
                            Name = "Neurología"
                        },
                        new
                        {
                            Id = new Guid("5e2a8c1d-4b73-4d96-a1f5-7c9b2e6d8a75"),
                            Description = "Área médica dedicada al diagnóstico y tratamiento de lesiones y enfermedades del sistema musculoesquelético.",
                            Name = "Traumatología"
                        },
                        new
                        {
                            Id = new Guid("9d4f1a7b-2c85-4e31-b6d7-5a8c3f2e9b86"),
                            Description = "Especialidad orientada a la salud del aparato reproductor femenino y la prevención de enfermedades asociadas.",
                            Name = "Ginecología"
                        },
                        new
                        {
                            Id = new Guid("2f7b6c1a-9d34-4a85-b7e2-8c5d1f9a3b97"),
                            Description = "Especialidad médica encargada de la prevención, diagnóstico y tratamiento de enfermedades de los ojos y la visión.",
                            Name = "Oftalmología"
                        },
                        new
                        {
                            Id = new Guid("7c3d8e5a-1f62-4b94-a9d3-6e2b7c1f4a08"),
                            Description = "Rama de la medicina que estudia y trata trastornos hormonales y enfermedades de las glándulas endocrinas.",
                            Name = "Endocrinología"
                        },
                        new
                        {
                            Id = new Guid("4a6e2b9c-8d15-4f73-b1c8-9e7a3d5f2b19"),
                            Description = "Especialidad médica dedicada al diagnóstico, tratamiento y prevención de trastornos mentales y emocionales.",
                            Name = "Psiquiatría"
                        },
                        new
                        {
                            Id = new Guid("6b1f9d3a-5c47-4e82-a7d5-2f8c6b1e3a20"),
                            Description = "Especialidad que aborda las enfermedades del oído, nariz, garganta y estructuras relacionadas.",
                            Name = "Otorrinolaringología"
                        });
                });

            modelBuilder.Entity("Dsw2026Ej15.Domain.Doctor", b =>
                {
                    b.HasOne("Dsw2026Ej15.Domain.Speciality", "Speciality")
                        .WithMany()
                        .HasForeignKey("SpecialityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Speciality");
                });
#pragma warning restore 612, 618
        }
    }
}
